### ISSUE TITLE
Publish on Plugin Portal

### ISSUE THREAD

**Issue by junichi11** [junichi11/netbeans-github-issues-plugin#16]
I'll publish this plugin on NetBeans Plugin Portal later.

**Comment by junichi11** [comment]
I've just published this plugin on Plugin Portal. It will be shown a little later.

**Comment by junichi11** [comment]
It's available on PP :+1: 
http://plugins.netbeans.org/plugin/57646/github-issues

**Comment by raoulvdberge** [comment]
:+1:
