### ISSUE TITLE
Edit issues: Label element too large

### ISSUE THREAD

**Issue by markiewb** [junichi11/netbeans-github-issues-plugin#17]
![2015-03-13_17h25_361](https://cloud.githubusercontent.com/assets/1857095/6642701/f6a1062e-c9a6-11e4-8245-bec669ab35ae.png)

**Comment by junichi11** [comment]
It is changed along a window size. 5 columns are shown per row.
Why is it a problem?

**Comment by markiewb** [comment]
It is low prio. I only wondered why it is so large.

**Comment by junichi11** [comment]
I don't change it at the moment because I think that it isn't important. But I'll increase the number of column if I change it.
