### ISSUE TITLE
"Assign to me" action in "Edit issue" and in context menu

### ISSUE THREAD

**Issue by markiewb** [junichi11/netbeans-github-issues-plugin#19]
![2015-03-13_17h25_36](https://cloud.githubusercontent.com/assets/1857095/6642723/2e6e41ac-c9a7-11e4-876f-8a758ce8f825.png)

**Comment by junichi11** [comment]
I'll add it not there but below the combobox.

**Comment by junichi11** [comment]
Done. NOTE: Probably, we can't add an action to context menu at the moment.

**Comment by junichi11** [comment]
![nb-github-issues-assign-yourself](https://cloud.githubusercontent.com/assets/738383/6648839/46ffddea-ca22-11e4-9d03-83614f1fa121.png)
