### ISSUE TITLE
Show github images for users

### ISSUE THREAD

**Issue by markiewb** [junichi11/netbeans-github-issues-plugin#20]

**Comment by junichi11** [comment]
Done.
![nb-github-issues-user-icons](https://cloud.githubusercontent.com/assets/738383/6650218/9510e46c-ca49-11e4-9ca0-9bf60651f0f1.png)

**Comment by junichi11** [comment]
@markiewb I've created a new nbm. Other issues are also contained. Please try to use it if possible :)

https://github.com/junichi11/netbeans-github-issues-plugin/releases/tag/v0.1.0 

Thanks!

**Comment by markiewb** [comment]
Thank you. It looks much nicer than before. Now you even show the color of the tags in the taglist. Good job!

**Comment by raoulvdberge** [comment]
Really loving the new changes :thumbsup:
