### ISSUE TITLE
ClassCastException when finding tasks ("no:-" filter is used)

### ISSUE THREAD

**Issue by markiewb** [junichi11/netbeans-github-issues-plugin#22]
![2015-03-14_10h15_25](https://cloud.githubusercontent.com/assets/1857095/6651076/1d3584a4-ca33-11e4-8784-8fdb6353a992.png)

Using 0.1.0

**Comment by markiewb** [comment]
BTW: 
* How can I search for issues assigned to a specific milestone? 
* How can I search for issues not assigned to a specific milestone? 
* How can I search for issues not assigned to any milestone?

**Comment by junichi11** [comment]
I'll fix it. Thanks!

**Comment by junichi11** [comment]
> BTW:
> 
> How can I search for issues assigned to a specific milestone?
> How can I search for issues not assigned to a specific milestone?
> How can I search for issues not assigned to any milestone?

Sorry, query feature is not perfect yet. I have to improve it...

We can get issues using 2 ways (Issues API, Search API).

- Issues API : https://developer.github.com/v3/issues/#list-issues-for-a-repository (not supported yet in the query feature)
- Search API : https://developer.github.com/v3/search/#search-issues (supported but need a few improvement)

I think that you can resolve some your requests using Issues API. So, I'll support it. But please wait a while...

**Comment by junichi11** [comment]
Fixed. 

https://github.com/junichi11/netbeans-github-issues-plugin/releases/tag/v0.1.0 (0.1.0.1)

**Comment by junichi11** [comment]
@markiewb 
> Search API : https://developer.github.com/v3/search/#search-issues (supported but need a few improvement)

The Milestone parameter doesn't exist in the document. However, I've confirmed that it is available. So, I just add it.

Thanks!
