### ISSUE TITLE
On issue close, description of issue is removed

### ISSUE THREAD

**Issue by raoulvdberge** [junichi11/netbeans-github-issues-plugin#24]
Steps to reproduce:

* Open an issue through Github itself.
* Add a commit, and mark the issue as solved in the commit dialog
* Push
* Description of the issue is gone on issue page on Github itself!

Running v0.1.1.

**Comment by junichi11** [comment]
> Push

On NetBeans? , your terminal?

I cannot reproduce it...


#### my steps

1. Create a new issue on a GitHub repository
![nb-github-issues-issue24-1](https://cloud.githubusercontent.com/assets/738383/6973528/6f82f654-d9c6-11e4-9abb-38995140a7dc.png)

2. Commit something
![nb-github-issues-issue24-2](https://cloud.githubusercontent.com/assets/738383/6973548/8739782c-d9c6-11e4-8149-e14b07456b61.png)

3. Push
![nb-github-issues-issue24-3](https://cloud.githubusercontent.com/assets/738383/6973560/9a4518f4-d9c6-11e4-8d8e-45b678a0c3c3.png)

4. Check the issue on the GitHub site
![nb-github-issues-issue24-4](https://cloud.githubusercontent.com/assets/738383/6973580/b4a976c2-d9c6-11e4-947d-1522edff8bf1.png)

#### my environments

Product Version: NetBeans IDE 8.0.2 (Build 201408251540)
Updates: NetBeans IDE is updated to version NetBeans 8.0.2 Patch 1
Java: 1.7.0_76; Java HotSpot(TM) Client VM 24.76-b04
Runtime: Java(TM) SE Runtime Environment 1.7.0_76-b13
System: Linux version 3.2.0-79-generic-pae running on i386; UTF-8; 


Could you provide your steps with screenshots in your test repository?

Thanks.

**Comment by raoulvdberge** [comment]
I pushed with Netbeans like in your screenshots.

But this is really strange, I'm not able to reproduce it now. I'll reopen when I see this issue again.
