### ISSUE TITLE
Add Pull Request support

### ISSUE THREAD

**Issue by junichi11** [junichi11/netbeans-github-issues-plugin#30]
Now, PR is show as an issue in a repository. So, we can just add comments and close it.

Supports for PRs should be added. (e.g. merge button)

- [x] Files Changed
- [x] Show Diff
- [x] Add Merge Button
- [x] Change an issue to a pull request
- [ ] Create a pull request

**Comment by junichi11** [comment]
![nb-github-issues-pr-1](https://cloud.githubusercontent.com/assets/738383/10250932/b013ec1e-6968-11e5-8efd-b42a46db5a95.png)

**Comment by junichi11** [comment]
![nb-github-issues-pr-2](https://cloud.githubusercontent.com/assets/738383/10250988/f6f73000-6968-11e5-93bf-f957d725e916.png)

![nb-github-issues-pr-3](https://cloud.githubusercontent.com/assets/738383/10250991/fb8a465c-6968-11e5-98cb-b81a8c66be81.png)

**Comment by raoulvdberge** [comment]
Very nice work :+1:

**Comment by junichi11** [comment]
:smile:

**Comment by junichi11** [comment]
Change an issue to a pull request.

![nb-github-issues-change-to-pull-request](https://cloud.githubusercontent.com/assets/738383/10271179/9f1f56d8-6b42-11e5-9997-55fb22a7b77e.png)
