### ISSUE TITLE
In the Tasks bar, custom queries are incorrectly updated

### ISSUE THREAD

**Issue by Seranth** [junichi11/netbeans-github-issues-plugin#44]
My own custom queries show a total number of 0 results, even if when I enter the query and do a search and it clearly finds all the wanted issues.

It's not just that the number is incorrect, they don't show when the folder is expanded either. The standard "Open" query functions properly, but custom ones do not update correctly, even if they find the issues when you enter the search area.

**Comment by junichi11** [comment]
It's reproducible. Thanks for reporting it!
I'll fix it.

**Comment by junichi11** [comment]
Fixed.
https://github.com/junichi11/netbeans-github-issues-plugin/releases/tag/v0.2.3

Thanks!

**Comment by Seranth** [comment]
Great :)

Will you update the plugin in the netbeans plugins portal so i can update it directly through the IDE or will I need to install the updated version manually?

**Comment by junichi11** [comment]
I'll do it later :) But you have to wait a little while because it needs verification.

**Comment by junichi11** [comment]
Uploaded to the PP :)
http://plugins.netbeans.org/plugin/57646/github-issues

**Comment by Seranth** [comment]
Awesome work man! Thanks!! :D
