### ISSUE TITLE
Can't add a Milestone from within Netbeans

### ISSUE THREAD

**Issue by rob1grie** [junichi11/netbeans-github-issues-plugin#46]
While viewing an issue in Netbeans (v 8.2), I try to add a Milestone from within the issue. When I click OK from within the New Milestone dialog I get "Can't add a milestone". I'm also not seeing Milestones that I've created online in my GitHub repository being available in the Milestone dropdown in an issue's edit page within Netbeans.

**Comment by junichi11** [comment]
Thanks for reporting!
Fixed in https://github.com/junichi11/netbeans-github-issues-plugin/commit/df7dc7b5f39c71554429e0ad047c6a2aa40925ad
