### ISSUE TITLE
GitHub Enterprise

### ISSUE THREAD

**Issue by cbm64chris** [junichi11/netbeans-github-issues-plugin#50]
Does this plugin work with Enterprise GitHub Repos?

I have followed the instructions and generated a personal OAuth Token but I am unable to connect to the repo. What form should the Name and Repository fields take?

Thanks

**Comment by junichi11** [comment]
> Does this plugin work with Enterprise GitHub Repos?

Unfortunately, No. Probably, a hostname setting must be added. I'll try to look at it later.

Thanks.

**Comment by junichi11** [comment]
I've added a `Hostname` text field. Just give it a try :) (0.3.0.1-dev)
https://github.com/junichi11/netbeans-github-issues-plugin/releases/tag/v0.3.0

If you find a problem, please let me know.
Thanks.

**Comment by cbm64chris** [comment]
Wow, quick 🥇 

I have the API URL for our enterprise GitHub and I have confirmed it by creating a token on the command line with the repo scope.

```
curl https://github.mycompany.com/api/v3/authorizations --user "myuser" --data '{"scopes":["repo"],"note":"Test"}'
```

Do you have an example of a config you have so I can make sure I have all the fields filled out correctly?

![screen shot 2018-02-22 at 11 49 46 am](https://user-images.githubusercontent.com/20171342/36537097-0752f308-17c7-11e8-83b9-a2a910bb48cd.png)

Redacted values obviously!

**Comment by junichi11** [comment]
Hostname is `github.mycompany.com` :)

**Comment by junichi11** [comment]
Steps:
1. Input your hostname
2. Input OAuth Token
3. Click Add Repository button

**Comment by cbm64chris** [comment]
Yup, I got it...should not have used the api as the host. I have connected to the repo and I am testing it now 👍

**Comment by junichi11** [comment]
Great to hear!

**Comment by cbm64chris** [comment]
Hey dude, did this make it into the main release?

**Comment by junichi11** [comment]
Yes.
