### ISSUE TITLE
Wrong commit IDs used for diff

### ISSUE THREAD

**Issue by AndreyLebedenko** [junichi11/netbeans-github-issues-plugin#51]
All `Diff` windows are empty since all commit IDs are wrongly selected.

![screen shot 2018-04-25 at 14 24 00](https://user-images.githubusercontent.com/19183908/39250274-66049814-4898-11e8-9965-c05b36d5d5d5.png)
![screen shot 2018-04-25 at 14 32 56](https://user-images.githubusercontent.com/19183908/39250288-698e0ec0-4898-11e8-86e5-fd07f24ddfe1.png)

**Comment by junichi11** [comment]
Thanks for reporting it!

**Comment by junichi11** [comment]
Unfortunately, I have no good idea to fix this problem at the moment.(Maybe, we can get sha ids from diff file. But if the same name files exist the same commit, that would be complex.)
So, I'll just disable this feature, sorry.

**Comment by junichi11** [comment]
Disabled.
https://github.com/junichi11/netbeans-github-issues-plugin/releases/tag/v0.3.2

Thanks for your understanding.
