### ISSUE TITLE
The way to get GitHub OAuth Token has been changed?

### ISSUE THREAD

**Issue by humphreygao** [junichi11/netbeans-github-issues-plugin#54]
I generate my access token from Settings > **Developer settings** > Personal access tokens > Generate new token，not from Settings > **Applications** > Personal access tokens > Generate new token that you mentioned in [README.md](https://github.com/junichi11/netbeans-github-issues-plugin#github-oauth-token). Could you check it.

**Comment by junichi11** [comment]
Thank you for letting me know :) It seems that it was moved there. I'll fix it.

**Comment by junichi11** [comment]
Fixed: https://github.com/junichi11/netbeans-github-issues-plugin/commit/f4ee0a4b5088284dbf36bf12c81df39f6c28b316.
Thanks!
