### ISSUE TITLE
Cannot update an issue with netbeans 8.2 and github issue plugin 0.3.3

### ISSUE THREAD

**Issue by icyhoty2k** [junichi11/netbeans-github-issues-plugin#57]
netbeans displays error message : the issue has not been updated

**Comment by junichi11** [comment]
I won't support NetBeans 8.2 anymore. So, please try using NetBeans 12.0.

**Comment by junichi11** [comment]
If you can reproduce it in NetBeans 12.0, please submit it as a new issue. Thanks!
