### ISSUE TITLE
Issues cannot marked as unseen

### ISSUE THREAD

**Issue by markiewb** [junichi11/netbeans-github-issues-plugin#7]
They seem to be always marked as "seen"

![image](https://cloud.githubusercontent.com/assets/1857095/5864860/7ed328b8-a285-11e4-8248-98f3feaf68c3.png)

**Comment by junichi11** [comment]
Sorry, this feature has not been implemented yet.

**Comment by junichi11** [comment]
I'll add this feature in NetBeans 8.1.
